# Site settings
title: Rytis Bagdžiūnas
email: rytis.bagdziunas@uclouvain.be
username: rbagd
description: "This is an a portfolio website for my academic projects. It includes lots of stuff related to my research."
baseurl: ""
url: "http://perso.uclouvain.be/rytis.bagdziunas/jekyll"

# Build settings
markdown: redcarpet
permalink: pretty
highlighter: true
