# Site settings
title: Alice Servais
email: alice.servais@kuleuven.be
username: aliceservais
description: "This is a portfolio website for my academic projects. It includes information related to my research."
url: http://alicemservais.eu

# Build settings
markdown: redcarpet
permalink: pretty
highlighter: pygments
exclude: ['posts', '_posts']
