# Site settings
title: Rytis Bagdžiūnas
email: rytis.bagdziunas@uclouvain.be
username: rbagd
description: "This is a portfolio website for my academic projects. It includes information related to my research."
baseurl: "http://perso.uclouvain.be/rytis.bagdziunas"
url: "http://perso.uclouvain.be/rytis.bagdziunas"

# Build settings
markdown: redcarpet
permalink: pretty
highlighter: true
exclude: ['posts', '_posts']
